name: Deploy Pipeline

on:
  workflow_dispatch:

jobs:
  deploy_dev:
    name: Deploy to Dev
    uses: pmcmanaman/called-test/.github/workflows/reusable-deploy.yml@main
    with:
      environment: dev
    secrets: inherit
